package UITeacher;


import UIStudent.*;
import UIAdmin.*;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pc
 */
public class DashboardTeacher extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public DashboardTeacher() {
        initComponents();
        showLogo();
        showDashboard();
    }
    
     public DashboardTeacher(int id) {
        initComponents();
        showLogo();
        showDashboard();
    }
    
    public void showLogo()
    {
        ImageIcon imageIcon = new ImageIcon("image/logohuit.jpg");
        Image image = imageIcon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
        lbLogo.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        itemLogo = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        itemDashboard = new javax.swing.JPanel();
        lbDashboard = new javax.swing.JLabel();
        itemClass = new javax.swing.JPanel();
        lbClass = new javax.swing.JLabel();
        itemLogout = new javax.swing.JPanel();
        lbLogout = new javax.swing.JLabel();
        itemSchedule = new javax.swing.JPanel();
        lbSchdule = new javax.swing.JLabel();
        itemMail = new javax.swing.JPanel();
        lbMail = new javax.swing.JLabel();
        layoutadmin = new javax.swing.JPanel();
        itemfrmMailTeacher = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        itemfrmClassTeacher = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        itemfrmDashboardTeacher = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        itemfrmScheduleTeacher = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        itemLogo.setBackground(new java.awt.Color(255, 255, 255));
        itemLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemLogoMouseClicked(evt);
            }
        });

        lbLogo.setAlignmentX(1.0F);

        javax.swing.GroupLayout itemLogoLayout = new javax.swing.GroupLayout(itemLogo);
        itemLogo.setLayout(itemLogoLayout);
        itemLogoLayout.setHorizontalGroup(
            itemLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemLogoLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        itemLogoLayout.setVerticalGroup(
            itemLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        itemDashboard.setBackground(new java.awt.Color(51, 51, 255));
        itemDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemDashboardMouseClicked(evt);
            }
        });

        lbDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lbDashboard.setText("Dashboard");

        javax.swing.GroupLayout itemDashboardLayout = new javax.swing.GroupLayout(itemDashboard);
        itemDashboard.setLayout(itemDashboardLayout);
        itemDashboardLayout.setHorizontalGroup(
            itemDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );
        itemDashboardLayout.setVerticalGroup(
            itemDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDashboardLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemClass.setBackground(new java.awt.Color(51, 51, 255));
        itemClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemClassMouseClicked(evt);
            }
        });

        lbClass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbClass.setForeground(new java.awt.Color(255, 255, 255));
        lbClass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbClass.setText("Class");
        lbClass.setToolTipText("");

        javax.swing.GroupLayout itemClassLayout = new javax.swing.GroupLayout(itemClass);
        itemClass.setLayout(itemClassLayout);
        itemClassLayout.setHorizontalGroup(
            itemClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbClass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );
        itemClassLayout.setVerticalGroup(
            itemClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemClassLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbClass)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemLogout.setBackground(new java.awt.Color(51, 51, 255));

        lbLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbLogout.setForeground(new java.awt.Color(255, 51, 51));
        lbLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogout.setText("LOGOUT");

        javax.swing.GroupLayout itemLogoutLayout = new javax.swing.GroupLayout(itemLogout);
        itemLogout.setLayout(itemLogoutLayout);
        itemLogoutLayout.setHorizontalGroup(
            itemLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemLogoutLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itemLogoutLayout.setVerticalGroup(
            itemLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemLogoutLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbLogout)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        itemSchedule.setBackground(new java.awt.Color(51, 51, 255));
        itemSchedule.setPreferredSize(new java.awt.Dimension(75, 45));
        itemSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemScheduleMouseClicked(evt);
            }
        });

        lbSchdule.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbSchdule.setForeground(new java.awt.Color(255, 255, 255));
        lbSchdule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSchdule.setText("schedule");

        javax.swing.GroupLayout itemScheduleLayout = new javax.swing.GroupLayout(itemSchedule);
        itemSchedule.setLayout(itemScheduleLayout);
        itemScheduleLayout.setHorizontalGroup(
            itemScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSchdule, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );
        itemScheduleLayout.setVerticalGroup(
            itemScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemScheduleLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbSchdule)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemMail.setBackground(new java.awt.Color(51, 51, 255));
        itemMail.setPreferredSize(new java.awt.Dimension(75, 45));
        itemMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemMailMouseClicked(evt);
            }
        });

        lbMail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbMail.setForeground(new java.awt.Color(255, 255, 255));
        lbMail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMail.setText("Mail");

        javax.swing.GroupLayout itemMailLayout = new javax.swing.GroupLayout(itemMail);
        itemMail.setLayout(itemMailLayout);
        itemMailLayout.setHorizontalGroup(
            itemMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbMail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );
        itemMailLayout.setVerticalGroup(
            itemMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemMailLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbMail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(itemLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(itemDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(itemClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(itemDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(itemLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(itemSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
            .addComponent(itemMail, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        jLabel12.setText("MAIL");

        javax.swing.GroupLayout itemfrmMailTeacherLayout = new javax.swing.GroupLayout(itemfrmMailTeacher);
        itemfrmMailTeacher.setLayout(itemfrmMailTeacherLayout);
        itemfrmMailTeacherLayout.setHorizontalGroup(
            itemfrmMailTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmMailTeacherLayout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(498, Short.MAX_VALUE))
        );
        itemfrmMailTeacherLayout.setVerticalGroup(
            itemfrmMailTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmMailTeacherLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        jLabel11.setText("CLASS");

        javax.swing.GroupLayout itemfrmClassTeacherLayout = new javax.swing.GroupLayout(itemfrmClassTeacher);
        itemfrmClassTeacher.setLayout(itemfrmClassTeacherLayout);
        itemfrmClassTeacherLayout.setHorizontalGroup(
            itemfrmClassTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmClassTeacherLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(468, Short.MAX_VALUE))
        );
        itemfrmClassTeacherLayout.setVerticalGroup(
            itemfrmClassTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmClassTeacherLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jLabel6.setText("Dashboard");

        javax.swing.GroupLayout itemfrmDashboardTeacherLayout = new javax.swing.GroupLayout(itemfrmDashboardTeacher);
        itemfrmDashboardTeacher.setLayout(itemfrmDashboardTeacherLayout);
        itemfrmDashboardTeacherLayout.setHorizontalGroup(
            itemfrmDashboardTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmDashboardTeacherLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(507, Short.MAX_VALUE))
        );
        itemfrmDashboardTeacherLayout.setVerticalGroup(
            itemfrmDashboardTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmDashboardTeacherLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        jLabel8.setText("SCHEDULE");

        javax.swing.GroupLayout itemfrmScheduleTeacherLayout = new javax.swing.GroupLayout(itemfrmScheduleTeacher);
        itemfrmScheduleTeacher.setLayout(itemfrmScheduleTeacherLayout);
        itemfrmScheduleTeacherLayout.setHorizontalGroup(
            itemfrmScheduleTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmScheduleTeacherLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(429, Short.MAX_VALUE))
        );
        itemfrmScheduleTeacherLayout.setVerticalGroup(
            itemfrmScheduleTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmScheduleTeacherLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layoutadminLayout = new javax.swing.GroupLayout(layoutadmin);
        layoutadmin.setLayout(layoutadminLayout);
        layoutadminLayout.setHorizontalGroup(
            layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layoutadminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itemfrmScheduleTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutadminLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(itemfrmDashboardTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
            .addGroup(layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutadminLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(itemfrmClassTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutadminLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(itemfrmMailTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layoutadminLayout.setVerticalGroup(
            layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layoutadminLayout.createSequentialGroup()
                .addComponent(itemfrmScheduleTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutadminLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(itemfrmDashboardTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutadminLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(itemfrmClassTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutadminLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(itemfrmMailTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(layoutadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layoutadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemDashboardMouseClicked
      showDashboard();
    }//GEN-LAST:event_itemDashboardMouseClicked

    private void itemClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemClassMouseClicked
        showClass();
    }//GEN-LAST:event_itemClassMouseClicked

    private void itemLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemLogoMouseClicked
        showDashboard();
    }//GEN-LAST:event_itemLogoMouseClicked

    private void itemScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemScheduleMouseClicked
        showSchedule();
    }//GEN-LAST:event_itemScheduleMouseClicked

    private void itemMailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemMailMouseClicked
        showMail();
    }//GEN-LAST:event_itemMailMouseClicked

    public void showDashboard()
    {
         itemfrmDashboardTeacher.setVisible(true);
         itemfrmScheduleTeacher.setVisible(false);
         itemfrmClassTeacher.setVisible(false);
         itemfrmMailTeacher.setVisible(false);
         lbDashboard.setForeground(Color.GRAY);
         lbSchdule.setForeground(Color.white);
         lbClass.setForeground(Color.white);
         lbMail.setForeground(Color.white);
    }
    
    public void showSchedule()
    {
         itemfrmDashboardTeacher.setVisible(false);
         itemfrmScheduleTeacher.setVisible(true);
         itemfrmClassTeacher.setVisible(false);
         itemfrmMailTeacher.setVisible(false);
         lbDashboard.setForeground(Color.white);
         lbSchdule.setForeground(Color.GRAY);
         lbClass.setForeground(Color.white);
         lbMail.setForeground(Color.white);
    }
    
  
    public void showClass()
    {
        itemfrmDashboardTeacher.setVisible(false);
         itemfrmScheduleTeacher.setVisible(false);
         itemfrmClassTeacher.setVisible(true);
         itemfrmMailTeacher.setVisible(false);
         lbDashboard.setForeground(Color.white);
         lbSchdule.setForeground(Color.white);
         lbClass.setForeground(Color.GRAY);
         lbMail.setForeground(Color.white);
    }
    
    public void showMail()
    {
        itemfrmDashboardTeacher.setVisible(false);
         itemfrmScheduleTeacher.setVisible(false);
         itemfrmClassTeacher.setVisible(false);
         itemfrmMailTeacher.setVisible(true);
         lbDashboard.setForeground(Color.white);
         lbSchdule.setForeground(Color.white);
         lbClass.setForeground(Color.white);
         lbMail.setForeground(Color.GRAY);
    }
    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel itemClass;
    private javax.swing.JPanel itemDashboard;
    private javax.swing.JPanel itemLogo;
    private javax.swing.JPanel itemLogout;
    private javax.swing.JPanel itemMail;
    private javax.swing.JPanel itemSchedule;
    private javax.swing.JPanel itemfrmClassTeacher;
    private javax.swing.JPanel itemfrmDashboardTeacher;
    private javax.swing.JPanel itemfrmMailTeacher;
    private javax.swing.JPanel itemfrmScheduleTeacher;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel layoutadmin;
    private javax.swing.JLabel lbClass;
    private javax.swing.JLabel lbDashboard;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbMail;
    private javax.swing.JLabel lbSchdule;
    // End of variables declaration//GEN-END:variables
}
