package UIStudent;


import UIAdmin.*;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pc
 */
public class DashboardStudent extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public DashboardStudent() {
        initComponents();
        showLogo();
        showDashboard();
    }
    
    public DashboardStudent(int id) {
        initComponents();
        showLogo();
        showDashboard();
    }
    
    public void showLogo()
    {
        ImageIcon imageIcon = new ImageIcon("image/logohuit.jpg");
        Image image = imageIcon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
        lbLogo.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        itemLogo = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        itemDashboard = new javax.swing.JPanel();
        lbDashboard = new javax.swing.JLabel();
        itemClass = new javax.swing.JPanel();
        lbClass = new javax.swing.JLabel();
        itemRegisterClass = new javax.swing.JPanel();
        lbRegister = new javax.swing.JLabel();
        itemPayment = new javax.swing.JPanel();
        lbPayment = new javax.swing.JLabel();
        itemLogout = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        itemSchedule = new javax.swing.JPanel();
        lbSchedule = new javax.swing.JLabel();
        itemMail = new javax.swing.JPanel();
        lbMail = new javax.swing.JLabel();
        layoutadmin = new javax.swing.JPanel();
        itemfrmRegisterStudent = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        itemfrmMailStudent = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        itemfrmClassStudent = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        itemfrmDashboardStudent = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        itemfrmPaymentStudent = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        itemfrmScheduleStudent = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        itemLogo.setBackground(new java.awt.Color(255, 255, 255));
        itemLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemLogoMouseClicked(evt);
            }
        });

        lbLogo.setAlignmentX(1.0F);

        javax.swing.GroupLayout itemLogoLayout = new javax.swing.GroupLayout(itemLogo);
        itemLogo.setLayout(itemLogoLayout);
        itemLogoLayout.setHorizontalGroup(
            itemLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemLogoLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        itemLogoLayout.setVerticalGroup(
            itemLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        itemDashboard.setBackground(new java.awt.Color(51, 51, 255));
        itemDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemDashboardMouseClicked(evt);
            }
        });

        lbDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lbDashboard.setText("Dashboard");

        javax.swing.GroupLayout itemDashboardLayout = new javax.swing.GroupLayout(itemDashboard);
        itemDashboard.setLayout(itemDashboardLayout);
        itemDashboardLayout.setHorizontalGroup(
            itemDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );
        itemDashboardLayout.setVerticalGroup(
            itemDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDashboardLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemClass.setBackground(new java.awt.Color(51, 51, 255));
        itemClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemClassMouseClicked(evt);
            }
        });

        lbClass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbClass.setForeground(new java.awt.Color(255, 255, 255));
        lbClass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbClass.setText("Class");
        lbClass.setToolTipText("");

        javax.swing.GroupLayout itemClassLayout = new javax.swing.GroupLayout(itemClass);
        itemClass.setLayout(itemClassLayout);
        itemClassLayout.setHorizontalGroup(
            itemClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbClass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );
        itemClassLayout.setVerticalGroup(
            itemClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemClassLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbClass)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemRegisterClass.setBackground(new java.awt.Color(51, 51, 255));
        itemRegisterClass.setPreferredSize(new java.awt.Dimension(75, 45));
        itemRegisterClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemRegisterClassMouseClicked(evt);
            }
        });

        lbRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbRegister.setForeground(new java.awt.Color(255, 255, 255));
        lbRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRegister.setText("Register class");

        javax.swing.GroupLayout itemRegisterClassLayout = new javax.swing.GroupLayout(itemRegisterClass);
        itemRegisterClass.setLayout(itemRegisterClassLayout);
        itemRegisterClassLayout.setHorizontalGroup(
            itemRegisterClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        itemRegisterClassLayout.setVerticalGroup(
            itemRegisterClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemRegisterClassLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbRegister)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemPayment.setBackground(new java.awt.Color(51, 51, 255));
        itemPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemPaymentMouseClicked(evt);
            }
        });

        lbPayment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPayment.setForeground(new java.awt.Color(255, 255, 255));
        lbPayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPayment.setText("Payment");

        javax.swing.GroupLayout itemPaymentLayout = new javax.swing.GroupLayout(itemPayment);
        itemPayment.setLayout(itemPaymentLayout);
        itemPaymentLayout.setHorizontalGroup(
            itemPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbPayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );
        itemPaymentLayout.setVerticalGroup(
            itemPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPaymentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbPayment)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemLogout.setBackground(new java.awt.Color(51, 51, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LOGOUT");

        javax.swing.GroupLayout itemLogoutLayout = new javax.swing.GroupLayout(itemLogout);
        itemLogout.setLayout(itemLogoutLayout);
        itemLogoutLayout.setHorizontalGroup(
            itemLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemLogoutLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itemLogoutLayout.setVerticalGroup(
            itemLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemLogoutLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        itemSchedule.setBackground(new java.awt.Color(51, 51, 255));
        itemSchedule.setPreferredSize(new java.awt.Dimension(75, 45));
        itemSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemScheduleMouseClicked(evt);
            }
        });

        lbSchedule.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbSchedule.setForeground(new java.awt.Color(255, 255, 255));
        lbSchedule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSchedule.setText("schedule");

        javax.swing.GroupLayout itemScheduleLayout = new javax.swing.GroupLayout(itemSchedule);
        itemSchedule.setLayout(itemScheduleLayout);
        itemScheduleLayout.setHorizontalGroup(
            itemScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSchedule, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );
        itemScheduleLayout.setVerticalGroup(
            itemScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemScheduleLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbSchedule)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemMail.setBackground(new java.awt.Color(51, 51, 255));
        itemMail.setPreferredSize(new java.awt.Dimension(75, 45));
        itemMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemMailMouseClicked(evt);
            }
        });

        lbMail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbMail.setForeground(new java.awt.Color(255, 255, 255));
        lbMail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMail.setText("Mail");

        javax.swing.GroupLayout itemMailLayout = new javax.swing.GroupLayout(itemMail);
        itemMail.setLayout(itemMailLayout);
        itemMailLayout.setHorizontalGroup(
            itemMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbMail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );
        itemMailLayout.setVerticalGroup(
            itemMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemMailLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbMail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(itemLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(itemDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemRegisterClass, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(itemLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(itemClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(itemRegisterClass, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
            .addComponent(itemPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(itemDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(itemLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(itemSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
            .addComponent(itemMail, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        jLabel13.setText("REGISTER");

        javax.swing.GroupLayout itemfrmRegisterStudentLayout = new javax.swing.GroupLayout(itemfrmRegisterStudent);
        itemfrmRegisterStudent.setLayout(itemfrmRegisterStudentLayout);
        itemfrmRegisterStudentLayout.setHorizontalGroup(
            itemfrmRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmRegisterStudentLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(511, Short.MAX_VALUE))
        );
        itemfrmRegisterStudentLayout.setVerticalGroup(
            itemfrmRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmRegisterStudentLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        jLabel12.setText("MAIL");

        javax.swing.GroupLayout itemfrmMailStudentLayout = new javax.swing.GroupLayout(itemfrmMailStudent);
        itemfrmMailStudent.setLayout(itemfrmMailStudentLayout);
        itemfrmMailStudentLayout.setHorizontalGroup(
            itemfrmMailStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmMailStudentLayout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(498, Short.MAX_VALUE))
        );
        itemfrmMailStudentLayout.setVerticalGroup(
            itemfrmMailStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmMailStudentLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        jLabel11.setText("CLASS");

        javax.swing.GroupLayout itemfrmClassStudentLayout = new javax.swing.GroupLayout(itemfrmClassStudent);
        itemfrmClassStudent.setLayout(itemfrmClassStudentLayout);
        itemfrmClassStudentLayout.setHorizontalGroup(
            itemfrmClassStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmClassStudentLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(468, Short.MAX_VALUE))
        );
        itemfrmClassStudentLayout.setVerticalGroup(
            itemfrmClassStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmClassStudentLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jLabel6.setText("Dashboard");

        javax.swing.GroupLayout itemfrmDashboardStudentLayout = new javax.swing.GroupLayout(itemfrmDashboardStudent);
        itemfrmDashboardStudent.setLayout(itemfrmDashboardStudentLayout);
        itemfrmDashboardStudentLayout.setHorizontalGroup(
            itemfrmDashboardStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmDashboardStudentLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(507, Short.MAX_VALUE))
        );
        itemfrmDashboardStudentLayout.setVerticalGroup(
            itemfrmDashboardStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmDashboardStudentLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        jLabel7.setText("PayMENT");

        javax.swing.GroupLayout itemfrmPaymentStudentLayout = new javax.swing.GroupLayout(itemfrmPaymentStudent);
        itemfrmPaymentStudent.setLayout(itemfrmPaymentStudentLayout);
        itemfrmPaymentStudentLayout.setHorizontalGroup(
            itemfrmPaymentStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmPaymentStudentLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(463, Short.MAX_VALUE))
        );
        itemfrmPaymentStudentLayout.setVerticalGroup(
            itemfrmPaymentStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmPaymentStudentLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        jLabel8.setText("SCHEDULE");

        javax.swing.GroupLayout itemfrmScheduleStudentLayout = new javax.swing.GroupLayout(itemfrmScheduleStudent);
        itemfrmScheduleStudent.setLayout(itemfrmScheduleStudentLayout);
        itemfrmScheduleStudentLayout.setHorizontalGroup(
            itemfrmScheduleStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmScheduleStudentLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE))
        );
        itemfrmScheduleStudentLayout.setVerticalGroup(
            itemfrmScheduleStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemfrmScheduleStudentLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layoutadminLayout = new javax.swing.GroupLayout(layoutadmin);
        layoutadmin.setLayout(layoutadminLayout);
        layoutadminLayout.setHorizontalGroup(
            layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layoutadminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itemfrmScheduleStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutadminLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(itemfrmPaymentStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(9, 9, 9)))
            .addGroup(layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutadminLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(itemfrmDashboardStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
            .addGroup(layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutadminLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(itemfrmClassStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutadminLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(itemfrmMailStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutadminLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(itemfrmRegisterStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layoutadminLayout.setVerticalGroup(
            layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layoutadminLayout.createSequentialGroup()
                .addComponent(itemfrmScheduleStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutadminLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(itemfrmPaymentStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutadminLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(itemfrmDashboardStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutadminLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(itemfrmClassStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutadminLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(itemfrmMailStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layoutadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutadminLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(itemfrmRegisterStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(layoutadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layoutadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemDashboardMouseClicked
      showDashboard();
    }//GEN-LAST:event_itemDashboardMouseClicked

    private void itemClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemClassMouseClicked
        showClass();
    }//GEN-LAST:event_itemClassMouseClicked

    private void itemRegisterClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemRegisterClassMouseClicked
        showRegisterClass();
    }//GEN-LAST:event_itemRegisterClassMouseClicked

    private void itemLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemLogoMouseClicked
        showDashboard();
    }//GEN-LAST:event_itemLogoMouseClicked

    private void itemPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemPaymentMouseClicked
       showPayment();
    }//GEN-LAST:event_itemPaymentMouseClicked

    private void itemScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemScheduleMouseClicked
        showSchedule();
    }//GEN-LAST:event_itemScheduleMouseClicked

    private void itemMailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemMailMouseClicked
        showMail();
    }//GEN-LAST:event_itemMailMouseClicked

    public void showDashboard()
    {
         itemfrmDashboardStudent.setVisible(true);
         itemfrmPaymentStudent.setVisible(false);
         itemfrmScheduleStudent.setVisible(false);
         itemfrmClassStudent.setVisible(false);
         itemfrmMailStudent.setVisible(false);
         itemfrmRegisterStudent.setVisible(false);
         lbDashboard.setForeground(Color.GRAY);
          lbSchedule.setForeground(Color.white);
           lbClass.setForeground(Color.white);
            lbMail.setForeground(Color.white);
             lbPayment.setForeground(Color.white);
              lbRegister.setForeground(Color.white);
    }
    
    public void showSchedule()
    {
         itemfrmDashboardStudent.setVisible(false);
         itemfrmPaymentStudent.setVisible(false);
         itemfrmScheduleStudent.setVisible(true);
         itemfrmClassStudent.setVisible(false);
         itemfrmMailStudent.setVisible(false);
         itemfrmRegisterStudent.setVisible(false);
         lbDashboard.setForeground(Color.white);
          lbSchedule.setForeground(Color.GRAY);
           lbClass.setForeground(Color.white);
            lbMail.setForeground(Color.white);
             lbPayment.setForeground(Color.white);
              lbRegister.setForeground(Color.white);
    }
    
    public void showPayment()
    {
         itemfrmDashboardStudent.setVisible(false);
         itemfrmPaymentStudent.setVisible(true);
         itemfrmScheduleStudent.setVisible(false);
         itemfrmClassStudent.setVisible(false);
         itemfrmMailStudent.setVisible(false);
         itemfrmRegisterStudent.setVisible(false);
         lbDashboard.setForeground(Color.white);
          lbSchedule.setForeground(Color.white);
           lbClass.setForeground(Color.white);
            lbMail.setForeground(Color.white);
             lbPayment.setForeground(Color.GRAY);
              lbRegister.setForeground(Color.white);
    }
    
    public void showClass()
    {
        itemfrmDashboardStudent.setVisible(false);
         itemfrmPaymentStudent.setVisible(false);
         itemfrmScheduleStudent.setVisible(false);
         itemfrmClassStudent.setVisible(true);
         itemfrmMailStudent.setVisible(false);
         itemfrmRegisterStudent.setVisible(false);
           lbDashboard.setForeground(Color.white);
          lbSchedule.setForeground(Color.white);
           lbClass.setForeground(Color.GRAY);
            lbMail.setForeground(Color.white);
             lbPayment.setForeground(Color.white);
              lbRegister.setForeground(Color.white);
    }
    
    public void showMail()
    {
        itemfrmDashboardStudent.setVisible(false);
         itemfrmPaymentStudent.setVisible(false);
         itemfrmScheduleStudent.setVisible(false);
         itemfrmClassStudent.setVisible(false);
         itemfrmMailStudent.setVisible(true);
         itemfrmRegisterStudent.setVisible(false);
           lbDashboard.setForeground(Color.white);
          lbSchedule.setForeground(Color.white);
           lbClass.setForeground(Color.white);
            lbMail.setForeground(Color.GRAY);
             lbPayment.setForeground(Color.white);
              lbRegister.setForeground(Color.white);
    }
    
    public void showRegisterClass()
    {
        itemfrmDashboardStudent.setVisible(false);
         itemfrmPaymentStudent.setVisible(false);
         itemfrmScheduleStudent.setVisible(false);
         itemfrmClassStudent.setVisible(false);
         itemfrmMailStudent.setVisible(false);
         itemfrmRegisterStudent.setVisible(true);
            lbDashboard.setForeground(Color.white);
          lbSchedule.setForeground(Color.white);
           lbClass.setForeground(Color.white);
            lbMail.setForeground(Color.white);
             lbPayment.setForeground(Color.white);
              lbRegister.setForeground(Color.GRAY);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel itemClass;
    private javax.swing.JPanel itemDashboard;
    private javax.swing.JPanel itemLogo;
    private javax.swing.JPanel itemLogout;
    private javax.swing.JPanel itemMail;
    private javax.swing.JPanel itemPayment;
    private javax.swing.JPanel itemRegisterClass;
    private javax.swing.JPanel itemSchedule;
    private javax.swing.JPanel itemfrmClassStudent;
    private javax.swing.JPanel itemfrmDashboardStudent;
    private javax.swing.JPanel itemfrmMailStudent;
    private javax.swing.JPanel itemfrmPaymentStudent;
    private javax.swing.JPanel itemfrmRegisterStudent;
    private javax.swing.JPanel itemfrmScheduleStudent;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel layoutadmin;
    private javax.swing.JLabel lbClass;
    private javax.swing.JLabel lbDashboard;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbMail;
    private javax.swing.JLabel lbPayment;
    private javax.swing.JLabel lbRegister;
    private javax.swing.JLabel lbSchedule;
    // End of variables declaration//GEN-END:variables
}
